central:
  reports:
    datastores:
      - artifact://yasu89/switch-bot-api-go
      - artifact://yasu89/switch-bot-mcp-server
  badges:
    datastores:
      - local://badges
  push:
    enable: true
